import Head from "next/head";

import { api } from "~/utils/api";

export default function Home() {
  const mangas = api.mangas.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {mangas.data && (
          <div className="flex flex-col items-center justify-center gap-4">
            <h1 className="text-2xl text-white">Mangas</h1>
            <ul className="flex flex-col gap-2">
              {mangas.data.map((manga) => (
                <li className="text-white" key={manga.id}>
                  <p>{manga.title} - {manga.author}</p>
                  <p>{manga.year} | Vol. {manga.volume}</p>
                  <ul>
                    {manga.frequencies.map((frequency, i) => (
                      <li key={`${manga.title}-${manga.volume}-${i}`}>{frequency.termTerm}: {frequency.count}</li>
                    ))}
                  </ul>
                </li>
              ))}
            </ul>
          </div>
        )}
      </main>
    </>
  );
}
