import Head from "next/head";
import PageWithTopbar from "~/components/PageWithTopbar";
import { api } from "~/utils/api";
import Frequencies from "~/components/Frequencies";
import { MangaCardInfo } from "~/components/MangaCard";

export default function Mangas() {
  const { data: library, isLoading } = api.libraries.getCurrentLibrary.useQuery();
  const { data: mangas } = api.mangas.getForLibrary.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <PageWithTopbar>
          <div className="flex flex-col max-w-[950px] mx-auto gap-4 p-8 bg-canvas">
            {(isLoading || !library) && <p>Loading...</p>}
            {library && (
              <>
                <div key={library.id} className="flex gap-8">
                  <div className="flex flex-col">
                    <h2 className="text-2xl font-semibold">Library</h2>
                  </div>
                  <div className="flex flex-col mt-6">
                    <span className="text-fgMuted italic mr-4">Length (in words):</span>
                    <span className="text-fgMuted italic mr-4">Unique Words:</span>
                    <span className="text-fgMuted italic mr-4">Unique Words (used once):</span>
                    <span className="text-fgMuted italic mr-4">Unique Words (used once %):</span>
                  </div>
                  <div className="flex flex-col mt-6">
                    <p className="text-fgDefault">{library.totalWords}</p>
                    <p className="text-fgDefault">{library.uniqueWords}</p>
                    <p className="text-fgDefault">{library.wordsUsedOnce}</p>
                    <p className="text-fgDefault">{library.wordsUsedOncePct}</p>
                  </div>
                </div>
                <hr/>
                <h2 className="text-2xl font-semibold">Mangas</h2>
                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
                  {mangas && mangas.map((manga) => (
                    <div key={manga.id} className="flex flex-col gap-4 rounded-lg border border-fgMuted p-4">
                      <MangaCardInfo key={manga.id} title={manga.title} author={manga.author} year={manga.year} />
                    </div>
                  ))}
                </div>
                <hr/>
                <Frequencies frequencies={library.frequencies} />
              </>
            )}
          </div>
        </PageWithTopbar>
      </main>
    </>
  );
}
